### ISSUE TITLE
Is it possible to flash with adb/flashboot after extracting the KDZ?

### ISSUE THREAD

**Issue by diegoviola** [ehem/kdztools#23]
The LG software is Windows only and I'm on a Linux machine, I'm curious if it's possible to flash using standard tools like adb/flashboot after extracting the KDZ.

If so, what's the procedure to reassemble the ROM to flash with those tools?

Thanks in advance.

**Comment by zimlokks** [comment]
Depends on what you plan to flash, I was able to flash both recovery.img and boot.img while using Ubuntu 17.10

**Comment by zimlokks** [comment]
Although I highly recommend using a VM (:

**Comment by diegoviola** [comment]
Yes, I was able to use QEMU to flash a new ROM, this is the command I used:

    qemu-system-x86_64 -enable-kvm -hda win7.qcow2 -m 4G -vga qxl -usb -device usb-tablet -device usb-ehci,id=ehci -device usb-host,hostbus=2,hostport=1

Just something I wanted to share: some tutorials I've seen recommend using `hostaddr` instead of `hostport`, but the LG software is so buggy that sometimes you have to reconnect the phone during the flashing procedure, and reconnecting the phone returns a new device ID and to use it you have to restart QEMU.

I strongly recommend using `hostport`, hostport allows you to actually specify the physical port of your computer, allowing you to reconnect the phone as many times as you want and the guest OS will still continue to see it.

Thanks.
