### ISSUE TITLE
I get a error when doing undz.py

### ISSUE THREAD

**Issue by doonoo** [ehem/kdztools#9]
`python undz.py -f kdzextracted/MS55010i_00.dz -x
[!] Error: extraneous data found IN pad
`

What does that mean?
https://drive.google.com/open?id=0B-IzaEtQa8ngV1g3SVRWU0JYa00 kdz file I'm referring too. This is for the LG Stylo 2 plus

**Comment by ehem** [comment]
This indicates the file wasn't formatted quite like undz.py was designed for.  Most likely this means the file is for a newer device and some portion which had previously been all zeros now has some data present.

This means I now get to look at the file and hopefully figure out what kind of new funkiness LG has come up with.  Hopefully this will be a quick fix.

**Comment by ehem** [comment]
For the moment I need to leave this new area marked as "unknown".  Merely doing that should be sufficient to extract this newer DZ file and I believe answers the originator's need.  Definitely a whack-a-mole situation.
